---
title: "Performance"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill

runtime: shiny
---

```{r, echo = FALSE}
library(magrittr)
library(readxl)
library(dplyr)
library(shiny)
library(flexdashboard)
```

```{r, label = "Load ticker database"}
data <- readxl::read_excel("D:/Aktier/Analyse/Perfomance/index.xlsx")
```

```{r, label = "Load index"}
df_stock <- kb.yahoo::load_data(ticker = data$Ticker, from = "2023-01-01", verbose = FALSE)
```


```{r, label = "Functions"}
summarise_return <- function(data) {
  
  data %>% 
    dplyr::filter(!is.na(Adjusted)) %>% 
    dplyr::summarise(N = dplyr::n(),
                     Start = dplyr::first(Adjusted), 
                     End = dplyr::last(Adjusted), 
                     Return = round(100 * (End - Start) / Start, 2),
                     SD = round(sd(ChangeSinceStart), 2),
                     SharpRatio = round(Return / SD, 2)
                     ) %>% 
    dplyr::select(-Start, -End)
  
}

summarise_return_by <- function(data, var) {
  
  data %>% 
    dplyr::filter(!is.na({{var}})) %>% 
    dplyr::group_by({{var}}) %>% 
    dplyr::summarise(N = round(mean(N), 1),
                     Return = round(mean(Return), 2), 
                     SD = round(mean(SD), 2), 
                     SharpRatio = round(mean(SharpRatio), 2)) %>% 
    dplyr::arrange(dplyr::desc(Return))
  
}

add_pct <- function(x) {
  
  paste0(x, " %")
  
}

get_first_day_in_this_month <- function() {
  
  paste0(substring(Sys.Date(), 1, 7), "-01") %>% 
    as.Date()
  
}

```

Overview {data-orientation=rows, data-icon="fa-list-ul"}
=====

```{r, label = "Reactive time period stock data"}

shiny::dateRangeInput(
  inputId = "date_stocks", 
  label = "Time period", 
  start = get_first_day_in_this_month(), 
  end = Sys.Date()
)

react_df_stock_input <- reactive({
  
  df_stock %>% 
    dplyr::filter(Date >= input$date_stocks[1] & Date <= input$date_stocks[2])
  
})

df_summary <- reactive({
  
  react_df_stock_input() %>% 
    dplyr::group_by(Ticker) %>% 
    summarise_return() %>% 
    dplyr::left_join(data %>% dplyr::select(-Link, -Correlation), by = "Ticker") %>% 
    dplyr::arrange(dplyr::desc(Return))
  
})
```


```{r, label = "Summarise stats", echo=FALSE, cache=TRUE}
  ## Best region
df_region <- reactive({
  df_summary() %>% 
    summarise_return_by(var = Region)
})

df_region_1 <- reactive({
  
  df_region() %>% 
    dplyr::slice(1)
  
})

## Best sektor
df_sector <- reactive({
  df_summary() %>% 
    summarise_return_by(var = Sektor)
})

df_sector_1 <- reactive({
  df_sector() %>% 
    dplyr::slice(1)
})

## Growth har v?ret bedst
df_type <- reactive({
  df_summary() %>% 
    summarise_return_by(var = GrowthVsValue)
})

df_type_1 <- reactive({
  df_type() %>% 
    dplyr::slice(1)
})

## Small har v?ret bedst
df_size <- reactive({
  df_summary() %>% 
    summarise_return_by(var = LargeVsSmall)
})

df_size_1 <- reactive({
  df_size() %>% 
    dplyr::slice(1)
})

## Mangler flere aktiv klasser
df_class <- reactive({
  df_summary() %>% 
    summarise_return_by(var = AktivKlasse)
})

df_class_1 <- reactive({
  df_class() %>% 
    dplyr::slice(1)
})

## Bedste investering
df_best_1 <- reactive({
  df_summary() %>% 
    dplyr::slice(1)
})

## D?rligste investering
df_worst_1 <- reactive({
  df_summary() %>% 
    dplyr::slice(dplyr::n())
})

## Mest risikable aktiv
df_risky <- reactive({
  df_summary() %>% 
    dplyr::filter(SD == max(SD))
})

## Mindst risikable aktiv
df_safe <- reactive({
  df_summary() %>% 
    dplyr::filter(SD == min(SD))
})
```

Row 
-----------------------------------------------------------------------

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_region_1()$Region),
     caption = div(
         tags$p("Best region"), 
         tags$h4(paste0("Afkast: ", df_region_1()$Return %>% add_pct()))
      ),
     icon = "fa-globe" 
  )
  
})
```
  
### 

```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_sector_1()$Sektor),
     caption = div(
         tags$p("Best Sector"), 
         tags$h4(paste0("Afkast: ", df_sector_1()$Return %>% add_pct()))
      ),
     icon = "fa-industry" 
  )
  
})
```

Row
-----------------------------------------------------------------------  

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_type_1()$GrowthVsValue),
     caption = div(
         tags$p("Growth vs value"), 
         tags$h4(paste0("Afkast: ", df_type_1()$Return %>% add_pct()))
      ),
     icon = "fa-balance-scale" 
  )
  
})
```

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_size_1()$LargeVsSmall),
     caption = div(
         tags$p("Large vs small cap"), 
         tags$h4(paste0("Afkast: ", df_size_1()$Return %>% add_pct()))
      ),
     icon = "fa-search" 
  )
  
})
```

Row
-----------------------------------------------------------------------  

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_best_1()$Investering),
     caption = div(
         tags$p("Best investment"), 
         tags$h4(paste0("Afkast: ", df_best_1()$Return %>% add_pct()))
      ),
     icon = "fa-diamond" 
  )
  
})
```

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_worst_1()$Investering),
     caption = div(
         tags$p("Worst investment"), 
         tags$h4(paste0("Afkast: ", df_worst_1()$Return %>% add_pct()))
      ),
     icon = "fa-thumbs-down" 
  )
  
})
```

Row
-----------------------------------------------------------------------  

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_safe()$Investering),
     caption = div(
         tags$p("Mindst risikoable investering"), 
         tags$h4(paste0("Risiko: ", df_safe()$SD %>% add_pct()))
      ),
     icon = "fa-shield" 
  )
  
})
```

### 
    
```{r}
flexdashboard::renderValueBox({
  
  valueBox(
    value = tags$p(df_risky()$Investering),
     caption = div(
         tags$p("Mest risikoable investering"), 
         tags$h4(paste0("Risiko: ", df_risky()$SD %>% add_pct()))
      ),
     icon = "fa-bomb" 
  )
  
})
```

Details {data-orientation=rows}
=====

Row
----------------------------------------------------------------------- 

### Region

```{r}
DT::renderDataTable(DT::datatable(df_region(), options = list(dom = "t")))
```

### Sector

```{r}
DT::renderDataTable(DT::datatable(df_sector(), options = list(dom = "t")))
```

Row
----------------------------------------------------------------------- 

### Type

```{r}
DT::renderDataTable(DT::datatable(df_type(), options = list(dom = "t")))
```

### Large vs Small cap

```{r}
DT::renderDataTable(DT::datatable(df_size(), options = list(dom = "t")))
```

World Index {data-orientation=rows}
=====

### Stock price
```{r}
df_stock %>% 
  dplyr::filter(Ticker == "SPYI.DE") %>% 
  plotly::plot_ly(x = ~Date, y = ~ChangeSinceStart, type = "scatter", mode = "lines")
```
